import type {Metadata} from "next";
import "./globals.css";
import {cn} from "@/lib/utils";
import {Navbar} from "@/components/layout/navbar";
import {Footer} from "@/components/layout/footer";
import {ThemeProvider} from "@/components/layout/theme-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
    <body className={cn("min-h-screen bg-background")}>
    <ThemeProvider
      attribute="class"
      defaultTheme="system"
      enableSystem
      //disableTransitionOnChange
    >
      <Navbar/>

      {children}

      <Footer/>
    </ThemeProvider>
    </body>
    </html>
  );
}
